# Generated by Django 5.2 on 2025-04-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
