# Generated by Django 5.2 on 2025-04-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_movies_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
