# Generated by Django 5.2 on 2025-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_alter_movies_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='star',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
